/* =========================================================================
   PLFC TOUCHLINE MANAGER — STATE
   Career state, save/load, and squad-depth helpers.
   ========================================================================= */

   const SAVE_KEY = "plfc_manager_save_v1";

   const Econ = {
     // Starting transfer kitty by club reputation tier.
     startBudget(tier) {
       return { 5: 80, 4: 45, 3: 25, 2: 12, 1: 5 }[tier] || 10;
     },
     // Per-matchweek broadcast/prize income trickle, scaled by tier.
     weeklyIncome(tier) {
       return Math.round(({ 5: 2.2, 4: 1.4, 3: 1.0, 2: 0.6, 1: 0.4 }[tier] || 0.8) * 10) / 10;
     },
     // End-of-season prize money by final league position (1-20).
     endOfSeasonPrize(position) {
       const base = 35 - position * 1.1;
       return Math.max(4, Math.round(base * 10) / 10);
     },
   };
   
   function ensureSquadDepth(club) {
     const need = { GK: 2, DF: 7, MF: 6, FW: 4 };
     const have = { GK: 0, DF: 0, MF: 0, FW: 0 };
     club.squad.forEach(p => have[p.pos]++);
     const baseRating = Math.max(58, 60 + club.tier * 2);
     for (const pos of POSITIONS) {
       while (have[pos] < need[pos]) {
         // Skew young: most fill-ins are academy-aged depth, with a handful of
         // older journeymen for squad balance.
         const age = Math.random() < 0.65 ? 17 + Math.floor(Math.random() * 6) : 24 + Math.floor(Math.random() * 10);
         const rating = baseRating - 6 + Math.floor(Math.random() * 10) - (age < 21 ? 4 : 0);
         const { name, nat } = randomProspect();
         const p = P(name, pos, age, rating, { nat });
         p.club = club.id;
         club.squad.push(p);
         have[pos]++;
       }
     }
   }
   
   function freshClubsCopy() {
     // Deep-ish copy so a new career never mutates the shared template data.
     const copy = CLUBS.map(c => ({
       ...c,
       // Clone stats/bonus too — a shallow {...p} would otherwise share those
       // objects with the shared CLUBS template and leak across careers.
       squad: c.squad.map(p => ({ ...p, stats: Stats.blank(), bonus: Stats.blankBonus() })),
     }));
     copy.forEach(ensureSquadDepth);
     return copy;
   }
   
   function newCareerState(managerName, clubId) {
     const clubs = freshClubsCopy();
     clubs.forEach(c => {
       c.budget = Econ.startBudget(c.tier);
       c.points = 0; c.played = 0; c.won = 0; c.drawn = 0; c.lost = 0;
       c.gf = 0; c.ga = 0;
       c.formation = "4-4-2";
       c.lineup = null; // filled by auto-pick on first use
     });
   
     return {
       managerName,
       clubId,
       season: 2026,
       week: 0,
       clubs,
       fixtures: [],          // generated by Season.buildFixtures
       results: [],           // completed match results this season
       market: [],            // current transfer market listings
       history: [],           // past season summaries {season, position, champion, ...}
       titles: 0,
       pendingMatch: null,    // result payload waiting to be viewed live
       feederPool: [...FEEDER_CLUBS_POOL],
       windowWasOpen: false,
     };
   }
   
   const Aging = {
     retirementChance(age, pos) {
       const effAge = pos === "GK" ? age - 2 : age;
       if (effAge < 33) return 0;
       if (effAge >= 39) return 1;
       return clamp01((effAge - 32) * 0.15);
     },
   
     growthStep(age) {
       if (age <= 20) return 2 + Math.round(Math.random() * 4); // +2..6
       if (age <= 23) return 1 + Math.round(Math.random() * 3); // +1..4
       if (age <= 26) return Math.round(Math.random() * 2);     // +0..2
       if (age <= 29) return Math.random() < 0.5 ? 1 : 0;
       return 0;
     },
     declineStep(age) {
       if (age < 30) return 0;
       if (age < 33) return Math.random() < 0.4 ? 1 : 0;
       if (age < 36) return 1 + Math.round(Math.random() * 2);  // +1..3
       return 2 + Math.round(Math.random() * 3);                // +2..5
     },
   
     // Ages every player across the league by one year, grows or declines
     // ratings, retires the oldest, and tops squads back up. Returns a news
     // digest for the season-end screen.
     advanceSeason(state) {
       const news = { retirements: [], breakouts: [], totalRetired: 0 };

       // Judge everyone's season BEFORE ratings move, then let it reshape both
       // potential and rating — relative to the player's own level, for every
       // club in the division.
       const perfIndex = Stats.performanceIndex(state, Season.table(state));

       state.clubs.forEach(club => {
         const survivors = [];
         club.squad.forEach(p => {
           p.age += 1;
           const retireChance = this.retirementChance(p.age, p.pos);
           if (p.age >= 43 || Math.random() < retireChance) {
             news.totalRetired++;
             if (club.id === state.clubId) news.retirements.push({ name: p.name, age: p.age, pos: p.pos });
             return; // not pushed to survivors — retires
           }
           const before = p.rating;
           const perf = perfIndex[p.id] || 0;

           // Performance reshapes the ceiling — a strong year raises potential,
           // a poor one trims it (bounded so a single season can't swing wildly).
           const potDelta = clamp(Math.round(perf * 6), -5, 5);
           p.potential = clamp(p.potential + potDelta, 40, 99);

           // Rating drift = age trajectory + the season's verdict. A good season
           // accelerates a young player's growth or cushions an old one's
           // decline; a poor season can pull anyone's overall down.
           let delta = 0;
           if (p.age < 30) {
             if (p.rating < p.potential) delta += this.growthStep(p.age);
           } else {
             delta -= this.declineStep(p.age);
           }
           delta += clamp(Math.round(perf * 3), -3, 3);
           p.rating = clamp(p.rating + delta, 40, 99);
           // A storming season can push a player past their old ceiling.
           if (p.rating > p.potential) p.potential = p.rating;

           if (club.id === state.clubId && p.rating - before >= 4) {
             news.breakouts.push({ name: p.name, age: p.age, from: before, to: p.rating });
           }
           survivors.push(p);
         });
         club.squad = survivors;
         ensureSquadDepth(club);
         // Ratings/values/wages drift, so keep them consistent with the new numbers.
         club.squad.forEach(p => {
           const rf = Math.max(0, p.rating - 55);
           const ageMult = p.age < 21 ? 1.35 : p.age < 24 ? 1.2 : p.age < 29 ? 1.0 : p.age < 32 ? 0.7 : p.age < 35 ? 0.45 : 0.25;
           p.value = Math.max(0.3, Math.round(Math.pow(rf, 1.7) * ageMult * 0.16 * 10) / 10);
           p.wage = Math.max(3, Math.round(Math.pow(rf, 1.45) * 2.6 + 4));
         });
         club.lineup = null; // force a fresh auto-pick against the new squad
       });
   
       return news;
     },
   };
   
   function clamp01(v) { return Math.max(0, Math.min(1, v)); }
   
   const Game = {
     state: null,
   
     save() {
       try {
         localStorage.setItem(SAVE_KEY, JSON.stringify(this.state));
         return true;
       } catch (e) {
         console.error("Save failed", e);
         return false;
       }
     },
     load() {
       try {
         const raw = localStorage.getItem(SAVE_KEY);
         if (!raw) return false;
         this.state = JSON.parse(raw);
         Stats.ensureAll(this.state); // backfill stats/bonus on saves predating them
         return true;
       } catch (e) {
         console.error("Load failed", e);
         return false;
       }
     },
     hasSave() {
       try { return !!localStorage.getItem(SAVE_KEY); } catch (e) { return false; }
     },
     clearSave() {
       try { localStorage.removeItem(SAVE_KEY); } catch (e) {}
     },
     start(managerName, clubId) {
       this.state = newCareerState(managerName, clubId);
       Season.buildFixtures(this.state);
       Market.weeklyUpdate(this.state);
       this.save();
     },
     myClub() {
       return this.state.clubs.find(c => c.id === this.state.clubId);
     },
   };