/* =========================================================================
   PLFC TOUCHLINE MANAGER — STATE
   Career state, save/load, and squad-depth helpers.
   ========================================================================= */

   const SAVE_KEY = "plfc_manager_save_v1";

   const Econ = {
     // Starting transfer kitty by club reputation tier.
     startBudget(tier) {
       return { 5: 80, 4: 45, 3: 25, 2: 12, 1: 5 }[tier] || 10;
     },
     // Per-matchweek broadcast/prize income trickle, scaled by tier.
     weeklyIncome(tier) {
       return Math.round(({ 5: 2.2, 4: 1.4, 3: 1.0, 2: 0.6, 1: 0.4 }[tier] || 0.8) * 10) / 10;
     },
     // End-of-season prize money by final league position (1-20).
     endOfSeasonPrize(position) {
       const base = 35 - position * 1.1;
       return Math.max(4, Math.round(base * 10) / 10);
     },
   };
   
   function ensureSquadDepth(club) {
     const need = { GK: 2, DF: 7, MF: 6, FW: 4 };
     const have = { GK: 0, DF: 0, MF: 0, FW: 0 };
     club.squad.forEach(p => have[p.pos]++);
     const baseRating = Math.max(58, 60 + club.tier * 2);
     for (const pos of POSITIONS) {
       while (have[pos] < need[pos]) {
         const age = 18 + Math.floor(Math.random() * 14);
         const rating = baseRating - 6 + Math.floor(Math.random() * 10);
         const p = P(randomName(), pos, age, rating);
         p.club = club.id;
         club.squad.push(p);
         have[pos]++;
       }
     }
   }
   
   function freshClubsCopy() {
     // Deep-ish copy so a new career never mutates the shared template data.
     const copy = CLUBS.map(c => ({
       ...c,
       squad: c.squad.map(p => ({ ...p })),
     }));
     copy.forEach(ensureSquadDepth);
     return copy;
   }
   
   function newCareerState(managerName, clubId) {
     const clubs = freshClubsCopy();
     clubs.forEach(c => {
       c.budget = Econ.startBudget(c.tier);
       c.points = 0; c.played = 0; c.won = 0; c.drawn = 0; c.lost = 0;
       c.gf = 0; c.ga = 0;
       c.formation = "4-4-2";
       c.lineup = null; // filled by auto-pick on first use
     });
   
     return {
       managerName,
       clubId,
       season: 2026,
       week: 0,
       clubs,
       fixtures: [],          // generated by Season.buildFixtures
       results: [],           // completed match results this season
       market: [],            // current transfer market listings
       history: [],           // past season summaries {season, position, champion, ...}
       titles: 0,
       pendingMatch: null,    // result payload waiting to be viewed live
       feederPool: [...FEEDER_CLUBS_POOL],
     };
   }
   
   const Game = {
     state: null,
   
     save() {
       try {
         localStorage.setItem(SAVE_KEY, JSON.stringify(this.state));
         return true;
       } catch (e) {
         console.error("Save failed", e);
         return false;
       }
     },
     load() {
       try {
         const raw = localStorage.getItem(SAVE_KEY);
         if (!raw) return false;
         this.state = JSON.parse(raw);
         return true;
       } catch (e) {
         console.error("Load failed", e);
         return false;
       }
     },
     hasSave() {
       try { return !!localStorage.getItem(SAVE_KEY); } catch (e) { return false; }
     },
     clearSave() {
       try { localStorage.removeItem(SAVE_KEY); } catch (e) {}
     },
     start(managerName, clubId) {
       this.state = newCareerState(managerName, clubId);
       Season.buildFixtures(this.state);
       Market.reroll(this.state);
       this.save();
     },
     myClub() {
       return this.state.clubs.find(c => c.id === this.state.clubId);
     },
   };